//! Native parts of the eSpeak NG Rust port.
//!
//! The safe API has no C dependencies. The `c-abi` feature lets the existing
//! engine use these implementations while the remaining pipeline is migrated.
// SPDX-License-Identifier: GPL-3.0-or-later

pub mod clause_engine;
pub mod clause_input;
pub mod clause_names;
pub mod clause_punctuation;
pub mod commands;
pub mod common_primitives;
pub mod common_text;
pub mod core_storage;
pub mod dictionary;
pub mod dictionary_storage;
pub mod encoding;
pub mod engine_io;
pub mod envelope;
pub mod events;
pub mod formant;
pub mod generate;
pub mod ieee80;
pub mod intonation;
pub mod language;
pub mod language_options;
pub mod lengths;
pub mod letters;
pub mod lookup;
pub mod mbrola;
pub mod mbrola_output;
pub mod mnemonics;
pub mod name_storage;
pub mod output;
pub mod phoneme;
pub mod phoneme_context;
pub mod phoneme_data;
pub mod phoneme_list;
pub mod phoneme_program;
pub mod phoneme_text;
pub mod phoneme_word;
pub mod rule_match;
pub mod rules;
pub mod smoothing;
pub mod sound_icons;
pub mod spectrum;
pub mod speed;
pub mod ssml;
pub mod ssml_clause;
pub mod ssml_control;
pub mod ssml_engine;
pub mod ssml_parameters;
pub mod ssml_prosody;
pub mod ssml_resource;
pub mod ssml_text;
pub mod ssml_voice;
pub mod suffix;
pub mod synthesis_parameters;
pub mod unicode;
pub mod utf8;
pub mod voice;
pub mod voice_backend;
pub mod voice_catalog;
pub mod voice_current;
pub mod voice_directive;
pub mod voice_load;
pub mod voice_reader;
pub mod voice_request;
pub mod voice_selection;
pub mod voice_setup;
pub mod voice_storage;
pub mod wave_memory;
pub mod wavegen;
pub mod word_key;
pub mod word_stress;

#[cfg(feature = "npu")]
pub mod acceleration;
#[cfg(feature = "proactor")]
pub mod async_queue;
#[cfg(feature = "proactor")]
pub mod audio_out;
#[cfg(feature = "proactor")]
pub mod data_io;
#[cfg(feature = "proactor")]
pub mod event_delivery;
#[cfg(feature = "proactor")]
pub mod resident;
#[cfg(feature = "proactor")]
pub mod synthesis_loop;

#[cfg(feature = "c-abi")]
mod ffi;
