// SPDX-License-Identifier: GPL-3.0-or-later
// Derived from eSpeak NG / ucd-tools, Copyright (C) 2012-2018 Reece H. Dunn.
// Unicode data: see COPYING.UCD. Preserve this fork's Unicode 11.0 semantics.
// Generated by tools/generate_rust_tables.py; do not edit by hand.
#![allow(clippy::unreadable_literal)]
pub(super) static CATEGORY_NAMES: &[&str] = &[
    "Cc\0", "Cf\0", "Cn\0", "Co\0", "Cs\0", "Ii\0", "Ll\0", "Lm\0", "Lo\0", "Lt\0", "Lu\0", "Mc\0",
    "Me\0", "Mn\0", "Nd\0", "Nl\0", "No\0", "Pc\0", "Pd\0", "Pe\0", "Pf\0", "Pi\0", "Po\0", "Ps\0",
    "Sc\0", "Sk\0", "Sm\0", "So\0", "Zl\0", "Zp\0", "Zs\0",
];
pub(super) static SCRIPT_NAMES: &[&str] = &[
    "Adlm\0", "Afak\0", "Aghb\0", "Ahom\0", "Arab\0", "Armi\0", "Armn\0", "Avst\0", "Bali\0",
    "Bamu\0", "Bass\0", "Batk\0", "Beng\0", "Bhks\0", "Blis\0", "Bopo\0", "Brah\0", "Brai\0",
    "Bugi\0", "Buhd\0", "Cakm\0", "Cans\0", "Cari\0", "Cham\0", "Cher\0", "Cirt\0", "Copt\0",
    "Cprt\0", "Cyrl\0", "Cyrs\0", "Deva\0", "Dogr\0", "Dsrt\0", "Dupl\0", "Egyd\0", "Egyh\0",
    "Egyp\0", "Elba\0", "Ethi\0", "Geok\0", "Geor\0", "Glag\0", "Gong\0", "Gonm\0", "Goth\0",
    "Gran\0", "Grek\0", "Gujr\0", "Guru\0", "Hang\0", "Hani\0", "Hano\0", "Hans\0", "Hant\0",
    "Hatr\0", "Hebr\0", "Hira\0", "Hluw\0", "Hmng\0", "Hrkt\0", "Hung\0", "Inds\0", "Ital\0",
    "Java\0", "Jpan\0", "Jurc\0", "Kali\0", "Kana\0", "Khar\0", "Khmr\0", "Khoj\0", "Knda\0",
    "Kore\0", "Kpel\0", "Kthi\0", "Lana\0", "Laoo\0", "Latf\0", "Latg\0", "Latn\0", "Lepc\0",
    "Limb\0", "Lina\0", "Linb\0", "Lisu\0", "Loma\0", "Lyci\0", "Lydi\0", "Mahj\0", "Maka\0",
    "Mand\0", "Mani\0", "Marc\0", "Maya\0", "Medf\0", "Mend\0", "Merc\0", "Mero\0", "Mlym\0",
    "Modi\0", "Mong\0", "Moon\0", "Mroo\0", "Mtei\0", "Mult\0", "Mymr\0", "Narb\0", "Nbat\0",
    "Newa\0", "Nkgb\0", "Nkoo\0", "Nshu\0", "Ogam\0", "Olck\0", "Orkh\0", "Orya\0", "Osge\0",
    "Osma\0", "Palm\0", "Pauc\0", "Perm\0", "Phag\0", "Phli\0", "Phlp\0", "Phlv\0", "Phnx\0",
    "Plrd\0", "Prti\0", "Qaak\0", "Rjng\0", "Rohg\0", "Roro\0", "Runr\0", "Samr\0", "Sara\0",
    "Sarb\0", "Saur\0", "Sgnw\0", "Shaw\0", "Shrd\0", "Sidd\0", "Sind\0", "Sinh\0", "Sogd\0",
    "Sogo\0", "Sora\0", "Soyo\0", "Sund\0", "Sylo\0", "Syrc\0", "Syre\0", "Syrj\0", "Syrn\0",
    "Tagb\0", "Takr\0", "Tale\0", "Talu\0", "Taml\0", "Tang\0", "Tavt\0", "Telu\0", "Teng\0",
    "Tfng\0", "Tglg\0", "Thaa\0", "Thai\0", "Tibt\0", "Tirh\0", "Ugar\0", "Vaii\0", "Visp\0",
    "Wara\0", "Wole\0", "Xpeo\0", "Xsux\0", "Yiii\0", "Zanb\0", "Zinh\0", "Zmth\0", "Zsym\0",
    "Zxxx\0", "Zyyy\0", "Zzzz\0",
];
