#!/usr/bin/env python3
"""Freeze this fork's initialized language presets into native Rust tables.

Only regeneration uses a C compiler. Cargo uses committed immutable tables.
All switch selectors and the default branch are covered. Wide tables are
exported as scalar/code-unit values, never native pointers or struct bytes.
"""
# SPDX-License-Identifier: GPL-3.0-or-later
import argparse
import json
import pathlib
import re
import subprocess
import tempfile

ROOT = pathlib.Path(__file__).resolve().parents[1]
CORE = ROOT / "src/libespeak-ng"
OPTIONS = {
    "dictionary_minimum": "dict_min_size", "dictionary_conditions": "dict_condition",
    "tone_flags": "0", "stress_lengths": "stress_lengths",
    "stress_amplitudes": "stress_amps", "word_gap": "langopts.word_gap",
    "vowel_pause": "langopts.vowel_pause", "stress_rule": "langopts.stress_rule",
    "stress_flags": "langopts.stress_flags", "unstressed_single": "langopts.unstressed_wd1",
    "unstressed_multiple": "langopts.unstressed_wd2", "parameters": "langopts.param",
    "numbers": "langopts.numbers", "numbers2": "langopts.numbers2",
    "thousands_separator": "langopts.thousands_sep", "decimal_separator": "langopts.decimal_sep",
    "intonation_group": "langopts.intonation_group", "tunes": "langopts.tunes",
    "lowercase_sentence": "langopts.lowercase_sentence", "spelling_stress": "langopts.spelling_stress",
}
SETTINGS = {name: "langopts." + name for name in (
    "break_numbers", "max_roman", "min_roman", "max_digits", "accents", "tone_language",
    "long_stop", "max_initial_consonants", "tone_numbers", "ideographs", "textmode",
    "dotless_i", "listx", "our_alphabet", "alt_alphabet", "alt_alphabet_lang",
    "max_lengthmod", "lengthen_tonic", "suffix_add_e")}
SETTINGS.update({name: name for name in ("transpose_min", "transpose_max", "encoding", "letter_bits_offset")})
ARRAYS = {"stress_lengths": (8, "i16"), "stress_amplitudes": (8, "u8"),
          "parameters": (18, "i32"), "tunes": (6, "u8"), "letter_bits": (256, "u8"),
          "punct_to_tone": (48, "u8")}
HEADER = """// SPDX-License-Identifier: GPL-3.0-or-later
// Derived from tr_languages.c and setlengths.c: Jonathan Duddington (2005-2015),
// Reece H. Dunn (2015-2016, 2020), Juho Hiltunen (2021).
// Generated by tools/generate_rust_languages.py; do not edit by hand.
use super::{Profile, Settings};
use crate::language_options::Options;
"""


def selectors(source):
    names = []
    for expression in re.findall(r"case\s+(L(?:3|4)?\([^)]*\))\s*:", source):
        name = "".join(re.findall(r"'([^'])'", expression))
        assert 2 <= len(name) <= 4, expression
        if name not in names:
            names.append(name)
    return sorted(names, key=lambda name: int.from_bytes(name.encode(), "big"))


def exporter(source):
    # Use the actual legacy UTF-8 implementation and length tables. No stubs
    # stand in for any configuration calculation. The Xextan punctuation array
    # lacks a C terminator; copy its declared one unit and add a native terminator.
    common = (CORE / "common.c").read_text()
    utf8 = common.split("int utf8_in2(int *c, const char *buf, int backwards)\n", 1)[1].split("/* End legacy UTF8 decoding.", 1)[0]
    lengths = (CORE / "setlengths.c").read_text().split("static const unsigned char length_mods_en[", 1)[1]
    prefix = '#include "translate.h"\n#include "synthesize.h"\n#include "setlengths.h"\n#include <stdio.h>\n#include <stdlib.h>\n#include <string.h>\n'
    prefix += 'char dictionary_name[40];\nint utf8_in2(int *c,const char *buf,int backwards)\n' + utf8
    prefix += '\nint utf8_in(int *c,const char *buf) {return utf8_in2(c,buf,0);}\n'
    prefix += '\nstatic const unsigned char length_mods_en[' + lengths
    prefix += '\n#include "tr_languages.c"\n'
    prefix += r'''
static void array(const void *pointer,int width,int count) {
    if(!pointer) {printf("null");return;}
    putchar('[');
    for(int i=0;i<count;i++) {
        if(i) putchar(',');
        long long value = width==1 ? ((const unsigned char*)pointer)[i] :
            width==2 ? ((const short*)pointer)[i] : ((const int*)pointer)[i];
        printf("%lld",value);
    }
    putchar(']');
}
static void bytes(const unsigned char *p) {array(p,1,p ? strlen((const char*)p)+1 : 0);}
static void wide(const wchar_t *p,int xextan) {
    if(!p) {printf("null");return;}
    int count=xextan ? 1 : wcslen(p);
    putchar('[');
    for(int i=0;i<count;i++) printf("%u,",(unsigned)p[i]);
    printf("0]");
}
static void profile(const char *name) {
    Translator *tr=SelectTranslator(name);
    if(!tr) abort();
    printf("{\"name\":\"%s\",",name);
'''
    for field, expr in {**OPTIONS, **SETTINGS}.items():
        expr = "0" if expr == "0" else "tr->" + expr
        prefix += f'printf("\\\"{field}\\\":");'
        if field in ARRAYS:
            count, kind = ARRAYS[field]
            width = {"u8": 1, "i16": 2, "i32": 4}[kind]
            prefix += f"array({expr},{width},{count});"
        elif field in ("dictionary_conditions", "stress_flags", "numbers", "numbers2", "break_numbers"):
            prefix += f'printf("%u",(unsigned)({expr}));'
        else:
            prefix += f'printf("%d",(int)({expr}));'
        prefix += "putchar(',');\n"
    prefix += r'''
printf("\"letter_bits\":");array(tr->letter_bits,1,256);
printf(",\"punct_to_tone\":");array(tr->punct_to_tone,1,48);
printf(",\"transpose_map\":");array(tr->transpose_map,1,tr->transpose_max-tr->transpose_min+1);
printf(",\"pairs\":");
int count=0;if(tr->frequent_pairs) {while(tr->frequent_pairs[count]!=0x7fff) count++;count++;}
array(tr->frequent_pairs,2,count);
printf(",\"lengths\":");array(tr->langopts.length_mods,1,100);
printf(",\"last_lengths\":");array(tr->langopts.length_mods0,1,100);
printf(",\"apostrophe\":");wide(tr->char_plus_apostrophe,0);
printf(",\"punctuation\":");wide(tr->punct_within_word,strcmp(name,"xex")==0);
printf(",\"ignored\":");count=0;while(tr->chars_ignore[count])count+=2;count+=2;
array(tr->chars_ignore,2,count);
printf(",\"groups\":[");for(int i=0;i<8;i++){if(i)putchar(',');wide(tr->letter_groups[i],0);}putchar(']');
printf(",\"ordinal\":");bytes((const unsigned char*)tr->langopts.ordinal_indicator);
printf(",\"roman\":");bytes(tr->langopts.roman_suffix);
if(tr->langopts.replace_chars) abort(); /* add an explicit schema before exporting new tables */
printf(",\"dictionary\":\"%s\"}\n",strcmp(name,tr->dictionary_name)==0?"":tr->dictionary_name);
free(tr);
}
int main(void) {
'''
    for name in ["", *selectors(source)]:
        prefix += f'profile("{name}");\n'
    return prefix + "return 0;\n}\n"


def generate(cc):
    source = (CORE / "tr_languages.c").read_text()
    with tempfile.TemporaryDirectory(prefix="espeak-rust-languages-") as temp:
        temp = pathlib.Path(temp)
        (temp / "config.h").write_text("")
        (temp / "export.c").write_text(exporter(source))
        subprocess.run([cc, "-O2", "-fwrapv", "-I", str(temp), "-I", str(CORE), "-I",
                        str(ROOT / "src/include"), str(temp / "export.c"), "-o", str(temp / "export")], check=True)
        profiles = [json.loads(line) for line in subprocess.check_output([str(temp / "export")], text=True).splitlines()]
    tables = {}
    declarations = []

    def table(values, kind, optional=False):
        if values is None:
            assert optional
            return "None"
        key = (kind, tuple(values))
        if key not in tables:
            name = f"TABLE_{len(tables)}"
            tables[key] = name
            declarations.append(f"pub(super) static {name}: [{kind}; {len(values)}] = [" + ",".join(map(str, values)) + "];\n")
            if kind == "u32":
                assert all(value <= 0xffff for value in values), "wchar_t compatibility requires explicit non-BMP policy"
                declarations.append(f"#[cfg(windows)]\npub(super) static {name}_WIDE: [u16; {len(values)}] = [" + ",".join(map(str, values)) + "];\n")
        return ("Some(&" + tables[key] + ")") if optional else "&" + tables[key]

    bodies = []
    for profile in profiles:
        body = "Profile {\n options: Options {\n"
        for field in OPTIONS:
            value = str(profile[field]).lower()
            body += f"{field}: {value},\n"
        body += "}, settings: Settings {\n"
        for field in SETTINGS:
            body += f"{field}: {profile[field]},\n"
        body += "},\n"
        for field, kind in (("letter_bits", "u8"), ("punct_to_tone", "u8"), ("transpose_map", "u8"),
                            ("pairs", "i16"), ("lengths", "u8"), ("last_lengths", "u8"), ("ignored", "u16"),
                            ("ordinal", "u8"), ("roman", "u8")):
            body += f"{field}: {table(profile[field], kind, field in ('transpose_map','pairs','ordinal'))},\n"
        for field in ("apostrophe", "punctuation"):
            body += f"{field}: {table(profile[field], 'u32')},\n"
            wide = table(profile[field], 'u32') + "_WIDE"
            body += f"#[cfg(windows)] {field}_wide: {wide},\n"
        body += "groups: [" + ",".join(table(g, "u32", True) for g in profile["groups"]) + "],\n"
        body += "#[cfg(windows)] groups_wide: [" + ",".join(table(g, "u32", True).replace(")", "_WIDE)") if g is not None else "None" for g in profile["groups"]) + "],\n"
        body += f'dictionary_override: b"{profile["dictionary"]}",\n}}'
        bodies.append(body)
    # A small immutable profile table is adequate; binary search selects codes.
    data = HEADER + "".join(declarations)
    data += "pub(super) static DEFAULT: Profile = " + bodies[0] + ";\n"
    data += "pub(super) static PROFILES: &[(u32, Profile)] = &[\n"
    for profile, body in zip(profiles[1:], bodies[1:]):
        code = int.from_bytes(profile["name"].encode(), "big")
        data += f"({code}, {body}),\n"
    data += "];\n"
    # Alphabet classification is independent of mutable engine state.
    alphabet_lines = source.split("static const ALPHABET alphabets[] = {", 1)[1].split("};", 1)[0]
    # Export separately through the same compiler rather than parsing macros.
    alphabet_export = exporter(source).rsplit("int main(void)", 1)[0]
    alphabet_export += 'int main(void) {for(int i=0;alphabets[i].name;i++) {const ALPHABET *a=&alphabets[i];printf("%s %d %u %u %d %d\\n",a->name,a->offset,a->range_min,a->range_max,a->language,a->flags);}return 0;}\n'
    assert alphabet_lines.strip()
    with tempfile.TemporaryDirectory(prefix="espeak-rust-alphabets-") as temp:
        temp = pathlib.Path(temp)
        (temp / "config.h").write_text("")
        (temp / "export.c").write_text(alphabet_export)
        subprocess.run([cc, "-O2", "-I", str(temp), "-I", str(CORE), "-I", str(ROOT / "src/include"),
                        str(temp / "export.c"), "-o", str(temp / "export")], check=True)
        alphabets = subprocess.check_output([str(temp / "export")], text=True).splitlines()
    data += "pub(super) static ALPHABETS: &[super::Alphabet] = &[\n"
    for line in alphabets:
        name, offset, first, last, language, flags = line.split()
        data += f'super::Alphabet {{name: b"{name}\\0", offset: {offset}, first: {first}, last: {last}, language: {language}, flags: {flags}}},\n'
    data += "];\n"
    with tempfile.TemporaryDirectory(prefix="espeak-rust-language-format-") as temp:
        target = pathlib.Path(temp) / "language_data.rs"
        target.write_text(data)
        subprocess.run(["rustfmt", "--edition", "2021", str(target)], check=True)
        return target.read_text()


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--cc", default="cc", help="host C compiler executable (default: cc)")
    parser.add_argument("--check", action="store_true", help="compare without writing")
    args = parser.parse_args()
    data = generate(args.cc)
    target = ROOT / "rust/language_data.rs"
    if args.check:
        if not target.exists() or target.read_text() != data:
            raise SystemExit(f"stale Rust language table: {target}")
    else:
        target.write_text(data)
    print("Rust language tables match C presets" if args.check else "Generated Rust language tables")


if __name__ == "__main__":
    main()
