#!/usr/bin/env python3
"""Snapshot this fork's Unicode/encoding data as native Rust constants.

The C implementation is only a development-time data oracle. Cargo builds
need neither Python nor a C compiler. Run with --check to verify provenance.
"""
# SPDX-License-Identifier: GPL-3.0-or-later
import argparse
import pathlib
import re
import subprocess
import tempfile

ROOT = pathlib.Path(__file__).resolve().parents[1]
UCD = ROOT / "src/ucd-tools"
HEADER = """// SPDX-License-Identifier: GPL-3.0-or-later
// Derived from eSpeak NG / ucd-tools, Copyright (C) 2012-2018 Reece H. Dunn.
// Unicode data: see COPYING.UCD. Preserve this fork's Unicode 11.0 semantics.
// Generated by tools/generate_rust_tables.py; do not edit by hand.
#![allow(clippy::unreadable_literal)]
"""
EXPORTER = r'''
#include <stdio.h>
#include <inttypes.h>
#include "ucd/ucd.h"
static uint64_t value(uint32_t c, int kind) {
    if (kind == -2) return ucd_lookup_category(c);
    if (kind == -1) return ucd_lookup_script(c);
    return ucd_properties(c, (ucd_category)kind);
}
static void table(const char *name, int kind) {
    uint32_t start = 0;
    uint64_t previous = value(0, kind);
    printf("pub(super) static %s: &[(u32, u32, u64)] = &[\n", name);
    for (uint32_t c = 1; c <= 0x110100; ++c) {
        uint64_t next = value(c, kind);
        if (next != previous) {
            if (kind < 0 || previous)
                printf("    (0x%x, 0x%x, 0x%" PRIx64 "),\n", start, c-1, previous);
            previous = next;
            start = c;
        }
    }
    if (kind < 0 || previous)
        printf("    (0x%x, 0xffffffff, 0x%" PRIx64 "),\n", start, previous);
    printf("];\n");
}
int main(void) {
    table("CATEGORIES", -2);
    table("SCRIPTS", -1);
    for (int cat = 0; cat <= UCD_CATEGORY_Zs; ++cat) {
        char name[32];
        snprintf(name, sizeof(name), "PROPERTIES_%d", cat);
        table(name, cat);
    }
    puts("pub(super) static PROPERTIES: &[&[(u32, u32, u64)]] = &[");
    for (int cat = 0; cat <= UCD_CATEGORY_Zs; ++cat) printf("    PROPERTIES_%d,\n", cat);
    puts("];");
    return 0;
}
'''


def generate(cc):
    result = {}
    with tempfile.TemporaryDirectory(prefix="espeak-rust-tables-") as temp:
        temp = pathlib.Path(temp)
        source = temp / "export.c"
        exe = temp / "export"
        source.write_text(EXPORTER)
        subprocess.run([cc, "-O2", "-I", str(UCD / "src/include"), str(source),
                        *[str(UCD / f"src/{name}.c") for name in
                          ("categories", "scripts", "proplist")], "-o", str(exe)], check=True)
        result["unicode_data.rs"] = HEADER + subprocess.check_output([str(exe)], text=True)
    case_source = (UCD / "src/case.c").read_text()
    cases = re.findall(r"\{\s*(0x[0-9A-Fa-f]+),\s*(0x[0-9A-Fa-f]+),\s*(0x[0-9A-Fa-f]+),\s*(0x[0-9A-Fa-f]+)\s*\}", case_source)
    assert cases
    result["unicode_case.rs"] = HEADER + "pub(super) static CASE: &[[u32; 4]] = &[\n" + "".join(
        "    [" + ", ".join(row) + "],\n" for row in cases) + "];\n"
    category_enum = (UCD / "src/include/ucd/ucd.h").read_text().split('typedef enum ucd_category_\n')[1].split('} ucd_category;')[0]
    names = re.findall(r'UCD_CATEGORY_(\w+),', category_enum)
    scripts_source = (UCD / "src/tostring.c").read_text()
    scripts = re.findall(r'"([A-Za-z]{4})"', scripts_source)
    result["unicode_names.rs"] = HEADER + "pub(super) static CATEGORY_NAMES: &[&str] = &[\n" + "".join(
        f'    "{name}\\0",\n' for name in names) + "];\n" + "pub(super) static SCRIPT_NAMES: &[&str] = &[\n" + "".join(
        f'    "{name}\\0",\n' for name in scripts) + "];\n"
    enc = (ROOT / "src/libespeak-ng/encoding.c").read_text()
    enums = re.findall(r'ESPEAKNG_ENCODING_(\w+)[,\s]', (ROOT / "src/include/espeak-ng/encoding.h").read_text().split('} espeak_ng_ENCODING;')[0])
    aliases = re.findall(r'\{ "([^"]+)",\s*ESPEAKNG_ENCODING_(\w+)\s*\}', enc)
    tables = re.findall(r'static const uint16_t (\w+)\[0x80\] = \{(.*?)\};', enc, re.S)
    body = HEADER + "pub(super) static ALIASES: &[(&str, u32)] = &[\n" + "".join(
        f'    ("{name}", {enums.index(encoding)}),\n' for name, encoding in aliases) + "];\n"
    by_name = {}
    for name, data in tables:
        data = re.sub(r'//[^\n]*', '', data)
        values = re.findall(r'0x[0-9a-fA-F]+', data)
        assert len(values) == 128, name
        by_name[name] = values
    body += "pub(super) static CODEPAGES: &[[u16; 128]] = &[\n"
    for name in enums[2:19]:
        body += f"    // {name}\n    [\n"
        for i in range(0, 128, 8):
            body += "        " + ", ".join(by_name[name][i:i + 8]) + ",\n"
        body += "    ],\n"
    body += "];\n"
    result["encoding_data.rs"] = body
    # Match the committed formatting without depending on cargo or the network.
    with tempfile.TemporaryDirectory(prefix="espeak-rustfmt-") as temp:
        for name, data in result.items():
            file = pathlib.Path(temp) / name
            file.write_text(data)
            subprocess.run(["rustfmt", "--edition", "2021", str(file)], check=True)
            result[name] = file.read_text()
    return result


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--cc", default="cc", help="host C compiler executable (default: cc)")
    parser.add_argument("--check", action="store_true", help="compare without writing")
    args = parser.parse_args()
    for name, data in generate(args.cc).items():
        target = ROOT / "rust" / name
        if args.check:
            if not target.exists() or target.read_text() != data:
                raise SystemExit(f"stale Rust table: {target}")
        else:
            target.write_text(data)
    print("Rust tables match the C data" if args.check else "Generated Rust tables")


if __name__ == "__main__":
    main()
